### PR TITLE
Update mission.md

### PR DESCRIPTION
**Pull request by Pilot-Pirx**
Updated text according to
https://cwiki.apache.org/confluence/display/OOOUSERS/The+Public+Service+Mission+of+Apache+OpenOffice

### CODE REVIEW

**Comment by marcus-aoo** [comment]
Looks good. Ready to merge if you want.

**Review by dave2wave — APPROVED** [review]

**Review by leginee — CHANGES_REQUESTED** [review]
I have some points I would like to add to this PR

- [ ] I am not able to find the menu item in the topnav menu. @marcus-aoo where do you activate it? it will not change with this PR

- [ ] we should add a blogpost too. I make a suggestion on the list

- [ ] it would be cool if the branch would be start with "preview/" so we can check the page

**Comment by marcus-aoo** [comment]
The menu item has still to be added in ".../gitbox.project-site/theme/openoffice/templates/topnav.html".
What I meant was the overview in ".../gitbox.project-site/PAGES.md".
Sorry for the confusion.

**Comment by Pilot-Pirx** [comment]
This is a simple PR about changing a text, not a branch.
If we want to add a menu entry we need to discuss where to add it.
And if someone wants a change, just do it! ;-)

**Comment by marcus-aoo** [comment]
I'll do it when the changed text is online.

**Comment by leginee** [comment]
I am not fond of this approach but it took so much time, to get to this point, that l do not want to block. so please go ahead

**Review by leginee — APPROVED** [review]

**Comment by Pilot-Pirx** [comment]
OK, if nobody wants to add something I will merge this PR on Monday evening.

**Comment by marcus-aoo** [comment]
As I know now where and how to add the menu item, I can do this also tomorrow evening.

**Comment by Pilot-Pirx** [comment]
But where do we want to add it?
Dave suggested "General", I suggested "Project". Still no feedback on this topic...

**Comment by marcus-aoo** [comment]
IMHO it's an overall thing, so "General" would fit best.

**Comment by pedlino** [comment]
> IMHO it's an overall thing, so "General" would fit best.

+1

**Pull request merged**
