### PR TITLE
Update base.html

### PR DESCRIPTION
**Pull request by Pilot-Pirx**
Remove external content

### CODE REVIEW

**Review by dave2wave — CHANGES_REQUESTED** [review]
Without these Javascript files the website will not function. These must be replaced with local copies.

**Comment by Pilot-Pirx** [comment]
This is long overdue, when do we want to do that?

**Comment by dave2wave** [comment]
> This is long overdue, when do we want to do that?

As part of this PR add in copies of the the 5 javascript/css files and properly link from base on these lines.

```
<link rel="stylesheet"
 	href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
 	integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
 	crossorigin="anonymous">
```
into
```
<link rel="stylesheet"
 	href="static/css/bootstrap.min.css">
```

**Comment by Pilot-Pirx** [comment]
If anyone is able to do that, please do so.
I will leave this PR open.

**Review by dave2wave — APPROVED** [review]

**Pull request merged**
